title: <img src="/images/favicon-w.png" /> Computing for COVID
url: "https://computingforcovid.io"
permalink: pretty
favicon: /images/favicon.png
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: chrisrhymes/bulma-clean-theme
exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      hide_hero: true
      hide_footer: true