#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Thank you for contributing your time and money to helping researchers with the
Computing for COVID DigitalOcean app. More information and the latest droplet
image can always be found at http://computingforcovid.io/

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
